services:
  model:
    image: "ziadnawar/remla-project:0.0.2"
  web:
    image: "ziadnawar/springbootserver" # from repo
    ports:
      - "8080:8080"
    environment:
      - MODEL_HOST=http://model:8081