apiVersion: apps/v1
kind: Deployment
metadata:
  name: classificiation-model-depl
  labels:
    app: classificiation-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: classificiation-model
  template:
    metadata:
      labels:
        app: classificiation-model
    spec:
      containers:
      - name: classificiation-model
        image: ziadnawar/remla-project:0.0.2
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: classificiation-model-svc
spec:
  selector:
    app: classificiation-model
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: classificiation-web-depl
  labels:
    app: classificiation-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: classificiation-web
  template:
    metadata:
      labels:
        app: classificiation-web
    spec:
      containers:
      - name: classificiation-web
        image: ziadnawar/springbootserver
        ports:
        - containerPort: 8080
        env:
          - name: MODEL_HOST
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: model.host
---
apiVersion: v1
kind: Service
metadata:
  name: classificiation-web-svc
spec:
  selector:
    app: classificiation-web
  ports:
    - port: 8080
      targetPort: 8080
---
#apiVersion: monitoring.coreos.com/v1
#kind: ServiceMonitor
#metadata:
#  name: mymonitor
#  labels:
#    release: promstack
#spec:
#  selector:
#    matchLabels:
#      app: classificiation-web-svc
#  endpoints:
#  - targetPort: 8080
#    path: "/metrics"
#    interval: 1s
#---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  defaultBackend:
    service:
      name: classificiation-web-svc
      port:
        number: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  model.host: "http://classificiation-model-svc:8081"