apiVersion: v1
kind: Pod
metadata:
 name: multilabel
 labels:
   app: multilabel
spec:
 containers:
 - name: multilabel
   image: zhariam/9-remla
   ports:
   - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
 name: multilabel-server
 labels:
   app: multilabel
spec:
 containers:
 - name: multilabel-server
   image: zhariam/9-remla-server
   ports:
   - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: multilabel-service
spec:
  type: NodePort
  selector:
    app: multilabel #covers pods with this label
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multilabel-ingress
spec:
  defaultBackend:
    service:
      name: multilabel-service
      port:
        number: 80 

# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: multilabel-deployment
#   labels:
#     app: multilabel
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: multilabel
#   template:
#     metadata:
#       labels:
#         app: multilabel
#     spec:
#       containers:
#       - name: multilabel
#         image: zhariam/9-remla
#         ports:
#         - containerPort: 80