  name: Merge to main check
  on: push
  jobs:
    init:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Setup python
          uses: actions/setup-python@v3
          with:
            python-version: 3.8.6 # pick 3.8.6 verion

        - name: Install dependencies
          run: |
            pip install -r requirements.txt --upgrade pip
            python -m nltk.downloader -d /usr/share/nltk_data all

        - name: debug pyenv
          run: echo ${{ steps.pyenv_installation.outputs.pyenv_root }}

        - name: run tests
          run: python -m pytest

        - name: run static analysis
          run: pylint --load-plugins=dslinter --disable=invalid-name,too-many-locals --max-line-length=120 --output-format=text:report.txt,colorized --reports=n src/

        - name: Archive static analysis report
          uses: actions/upload-artifact@v3
          with:
            name: generate-reports
            path: output/report.txt

        - name: Download a single artifact
          uses: actions/download-artifact@v3
          with:
            path: output
