  name: Multi-label-classification
  on: push
  jobs:
    init:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Setup python
          uses: actions/setup-python@v3
          with:
            python-version: 3.8.6 # pick 3.8.6 verion

        - name: Install dependencies
          run: |
            pip install -r requirements.txt --upgrade pip
            python -m nltk.downloader -d /usr/share/nltk_data all

        - name: debug pyenv
          run: echo ${{ steps.pyenv_installation.outputs.pyenv_root }}

        - name: run tests
          run: python -m pytest

        - name: run static analysis
          run: pylint --load-plugins=dslinter --disable=invalid-name,too-many-locals --max-line-length=120 --output-format=text:report.txt,colorized --reports=n src/

        - name: switching from HTTPS to SSH
          run: git remote set-url origin ${{ secrets.ssh }}

        - name: check for changes
          run: git status

        - name: stage changed files
          run: git add .

        - name: commit changed files
          run: git commit -m "Auto updating report.txt"

        - name: fetch from master
          run: git fetch origin main

        - name: push code to main
          run: git push origin HEAD:main