  name: Multi-label-classification
  on: push
  jobs:
    init:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install python version
          # use the pyenv-action version 7
          uses: gabrielfalcao/pyenv-action@v7

          with:
            default: 3.8.6 # pick 3.8.6 verion
            command: pip install -U pip  # upgrade pip after installing python

        - name: create environment
          run: pyenv local 3.8.6 && python -mvenv .venv386

        - name: Install dependencies
          run: pip install -r requirements.txt --upgrade pip

        - name: debug pyenv
          run: echo ${{ steps.pyenv_installation.outputs.pyenv_root }}

        - name: run static analysis
          run: pylint --load-plugins=dslinter --disable=invalid-name,too-many-locals --max-line-length=120 --output-format=text:report.txt,colorized --reports=n src/