  name: Full data validation
  on: 
    push:
      tags: ["v[0-9]+.[0-9]+.[0-9]+"]

  jobs:
    init:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Setup python
          uses: actions/setup-python@v3
          with:
            python-version: 3.8.6 # pick 3.8.6 verion

        - name: Install dependencies
          run: |
            pip install -r requirements.txt --upgrade pip
            python -m nltk.downloader -d /usr/share/nltk_data all

        - name: debug pyenv
          run: echo ${{ steps.pyenv_installation.outputs.pyenv_root }}

        - name: data validation
          run: data-validation.ipynb

